---
- hosts: 172.31.12.54
  become: yes 
  tasks:

  - name: i want to execute linux commands directly
    command: hostname -f
    register: myfirsttaskresult
  
  - name: i want to display the result of the first task 
    debug:
      msg: "{{myfirsttaskresult}}"

  - name: i want to instll git
    apt:
      name: git 
      state: present
    when: myfirsttaskresult.stderr ==""

  - name: i want to install tree
    apt:
      name: tree
      state: present
    when: myfirsttaskresult.stderr !=""