---
- hosts: 172.31.36.174
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to install apache2
    apt:
     name: apache2
     state: present

  - name: i want to copy static files into ansibel node side
    template: 
      src: mystaticfile.html
      dest: /var/www/html/index.html
  

  - name: i want to copy dynamic file into ansible nodes side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html