---
- hosts: mywebservers
  become: yes
  tasks:

  - name: install java on ubuntu
    apt:
      name: "{{myjavainstallonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on RedHat
    yum:
      name: "{{myjavainstallonRedHat}}"
      state: present
    when: ansible_os_family =="RedHat"