---
- hosts: 172.31.12.54
  become: yes
  tasks:

  - name: i want to install git
    apt:
      name: git
      state: present
    tags: mygit

  - name: i want to install tree
    apt:
      name: tree
      statee: present
    tags: mytree
    ignore_errors: yes

  - name: i want to install wget
    apt: 
      name: wget
      state: present
    tags: mywget