---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver on ubuntu
    apt: 
      name: "{{mywebpackonubutu}}"
      state: present
    when: ansible_os_family =="Debian"


  - name: start webserver on ubuntu
    service: 
      name: "{{mywebpackonubutu}}"
      state: restarted
    when: ansible_os_family =="Debian"
  
  - name: install webserver on RedHat
    yum: 
      name: "{{mywebserveronredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: start webserver on RedHat
    service:
      name: "{{mywebserveronredhat}}"
      state: started
    when: ansible_os_family =="RedHat"