---
- hosts: mywebservers
  become: yes
  tasks:


  - name: i want to downlode files from remote into node side
    get_url:
      url: https://github.com/kr1shnak/myAnsible-19-08-22/blob/3ff0c609aa2ad5fd6cfcef4d8739ef65dba0545b/myindex.j2
      dest: /var/www/html/index.html
      force_basic_auth: yes

