---
# tasks file for mytomcatrole

- include_tasks: myadduser.yml
- include_tasks: myjavainstall.yml
- include_tasks: installtomcat.yml
- include_tasks: permissions.yml
- include_tasks: tomadminusers.yml
- include_tasks: tomcatservice.yml
- include_tasks: tomcatstart.yml
- include_tasks: 
